/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaFamilia.java
 *
 * Created on 30/04/2011, 05:18:55 PM
 */
package pibxalapa;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author ivan
 */
public class AltaFamilia extends javax.swing.JInternalFrame {

    /** Creates new form AltaFamilia */
    public AltaFamilia() {
        initComponents();
        cargarMunicipiosyColonias();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_titulo = new javax.swing.JLabel();
        Label_fam = new javax.swing.JLabel();
        Label_No_Integrantes = new javax.swing.JLabel();
        Label_calle = new javax.swing.JLabel();
        Label_Colonia = new javax.swing.JLabel();
        Label_Municipio = new javax.swing.JLabel();
        familia_txt = new javax.swing.JTextField();
        num_integrantes_txt = new javax.swing.JTextField();
        telefono_txt = new javax.swing.JTextField(10);
        municipio_combo = new javax.swing.JComboBox();
        colonia_combo = new javax.swing.JComboBox();
        bt_cancelar_fam = new javax.swing.JButton();
        bt_guardar_fam = new javax.swing.JButton();
        Label_tel = new javax.swing.JLabel();
        calle_txt = new javax.swing.JTextField();
        bt_agregarmun = new javax.swing.JButton();
        bt_agregarcol = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alta de Familia");

        Label_titulo.setFont(new java.awt.Font("Verdana", 1, 14));
        Label_titulo.setText("Agregar nueva familia");

        Label_fam.setText("Familia:");

        Label_No_Integrantes.setText("No. de Integrantes:");

        Label_calle.setText("Calle y No.:");

        Label_Colonia.setText("Colonia:");

        Label_Municipio.setText("Municipio:");

        municipio_combo.setEditable(true);
        municipio_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipio_comboActionPerformed(evt);
            }
        });

        colonia_combo.setEditable(true);
        colonia_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colonia_comboActionPerformed(evt);
            }
        });

        bt_cancelar_fam.setText("Cancelar");
        bt_cancelar_fam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelar_famActionPerformed(evt);
            }
        });

        bt_guardar_fam.setText("Guardar");
        bt_guardar_fam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardar_famActionPerformed(evt);
            }
        });

        Label_tel.setText("Teléfono: ");

        bt_agregarmun.setText("Agregar");
        bt_agregarmun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarmunActionPerformed(evt);
            }
        });

        bt_agregarcol.setText("Agregar");
        bt_agregarcol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarcolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Label_calle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(calle_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Label_fam)
                                        .addGap(18, 18, 18)
                                        .addComponent(familia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_No_Integrantes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num_integrantes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_Colonia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(bt_guardar_fam, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(bt_cancelar_fam, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(colonia_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bt_agregarcol)
                                                .addGap(19, 19, 19)))))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Municipio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(municipio_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_agregarmun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_tel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_fam)
                    .addComponent(familia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_No_Integrantes)
                    .addComponent(num_integrantes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_calle)
                    .addComponent(Label_Colonia)
                    .addComponent(colonia_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calle_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_agregarcol))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Municipio)
                    .addComponent(municipio_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_tel)
                    .addComponent(bt_agregarmun))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_guardar_fam)
                    .addComponent(bt_cancelar_fam))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelar_famActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelar_famActionPerformed
        this.doDefaultCloseAction();
    }//GEN-LAST:event_bt_cancelar_famActionPerformed

    private void bt_guardar_famActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardar_famActionPerformed
       int errores = 0;
       
       String lista_errores = "";
       String familia = this.familia_txt.getText();
       String Num_integrantes = this.num_integrantes_txt.getText();
       String Calle = this.calle_txt.getText();
       String Colonia = (String) this.colonia_combo.getSelectedItem();
       String Municipio = (String)this.municipio_combo.getSelectedItem();
       String Telefono = this.telefono_txt.getText();
      
       if (familia.length() == 0) {
           errores++;
           lista_errores += "*La Familia no debe estar vacía\n";
       }
       
       
       if (Calle.length() == 0) {
           errores++;
           lista_errores += "*La Calle no debe estar vacía\n";
       }
       if (Num_integrantes.length() == 0) {
           Num_integrantes = "0";
       }
       
       
       if (Colonia.length() == 0) {
           errores++;
           lista_errores += "*La Colonia no debe estar vacía\n";
       }
       if (Municipio.length() == 0) {
           errores++;
           lista_errores += "*El Municipio no debe estar vacío\n";
       }
       
       if (Telefono.length() == 0) {
           errores++;
           lista_errores += "*El Teléfono no debe estar vacío\n";
       }
     
       
       
       if(errores == 0 ){
           Familia nuevafam = new Familia();
           nuevafam.Calle = Calle;
           nuevafam.Colonia = Colonia;
           nuevafam.Familia = familia;
           nuevafam.Municipio = Municipio;
           nuevafam.No_Integrantes = Integer.parseInt(Num_integrantes);
           nuevafam.Telefono = Telefono; 
           if (nuevafam.Registrar()){
               
               javax.swing.JOptionPane.showMessageDialog(null, "Familia Registrada de Forma Exitosa");
                this.familia_txt.setText("");
                this.num_integrantes_txt.setText("");
                this.calle_txt.setText("");
                this.colonia_combo.setSelectedItem("");
                this.municipio_combo.setSelectedItem("");
                this.telefono_txt.setText("");
           }else
           javax.swing.JOptionPane.showMessageDialog(null, lista_errores);
       }   
    }//GEN-LAST:event_bt_guardar_famActionPerformed

    private void bt_agregarmunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarmunActionPerformed
        String nuevoMun = (String) this.municipio_combo.getSelectedItem();
        try{
            
            Connection conexion = DriverManager.getConnection("jdbc:sqlite:"+System.getProperty("user.dir")+"/pibxalapa.db");
            Statement instruccion_insert = conexion.createStatement();
            String cad_sql = "insert into Municipio (Municipio) values ('"+nuevoMun+"')";
            instruccion_insert.executeUpdate(cad_sql);
            conexion.close();
        }catch (Exception e){
          javax.swing.JOptionPane.showMessageDialog(null, e.toString());              
        }
        cargarMunicipiosyColonias();        
    }//GEN-LAST:event_bt_agregarmunActionPerformed

    private void municipio_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipio_comboActionPerformed
        
    }//GEN-LAST:event_municipio_comboActionPerformed

    private void colonia_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colonia_comboActionPerformed

                   
    }//GEN-LAST:event_colonia_comboActionPerformed

    private void bt_agregarcolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarcolActionPerformed
        String nuevaCol = (String) this.colonia_combo.getSelectedItem();
        try{
        Connection conexion = DriverManager.getConnection("jdbc:sqlite:"+System.getProperty("user.dir")+"/pibxalapa.db");
        Statement instruccion_insert = conexion.createStatement();
        String cad_sql = "insert into Colonia (Colonia) values ('"+nuevaCol+"')";
        instruccion_insert.executeUpdate(cad_sql);
        conexion.close();
        }catch (Exception e){
          javax.swing.JOptionPane.showMessageDialog(null, e.toString());              
        }
        cargarMunicipiosyColonias();
    }//GEN-LAST:event_bt_agregarcolActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Colonia;
    private javax.swing.JLabel Label_Municipio;
    private javax.swing.JLabel Label_No_Integrantes;
    private javax.swing.JLabel Label_calle;
    private javax.swing.JLabel Label_fam;
    private javax.swing.JLabel Label_tel;
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JButton bt_agregarcol;
    private javax.swing.JButton bt_agregarmun;
    private javax.swing.JButton bt_cancelar_fam;
    private javax.swing.JButton bt_guardar_fam;
    private javax.swing.JTextField calle_txt;
    private javax.swing.JComboBox colonia_combo;
    private javax.swing.JTextField familia_txt;
    private javax.swing.JComboBox municipio_combo;
    private javax.swing.JTextField num_integrantes_txt;
    private javax.swing.JTextField telefono_txt;
    // End of variables declaration//GEN-END:variables

   public final void cargarMunicipiosyColonias(){
       try{
        colonia_combo.removeAllItems();
        municipio_combo.removeAllItems();
        Connection conexion = DriverManager.getConnection("jdbc:sqlite:"+System.getProperty("user.dir")+"/pibxalapa.db");
        Statement instruccion_select = conexion.createStatement();
        String cad_sql_col = "select Colonia from Colonia order by Colonia;";
        String cad_sql_mun = "select Municipio from Municipio order by Municipio;";
        ResultSet resultado_col = instruccion_select.executeQuery(cad_sql_col);
        instruccion_select.clearBatch();
      
        while (resultado_col.next()) {
            colonia_combo.addItem(resultado_col.getString("Colonia"));
            }
        resultado_col.close();
        ResultSet resultado_mun = instruccion_select.executeQuery(cad_sql_mun);
        while (resultado_mun.next()) {
            municipio_combo.addItem(resultado_col.getString("Municipio"));
            }
        resultado_mun.close();
        conexion.close();
        
        }catch (Exception e){
           javax.swing.JOptionPane.showMessageDialog(null, e.toString());
        }
                   
    
   }

}

