/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaHermano.java
 *
 * Created on 30/04/2011, 11:46:12 PM
 */
package pibxalapa;

/**
 *
 * @author ivan
 */
public class AltaHermano extends javax.swing.JInternalFrame {

    /** Creates new form AltaHermano */
    public AltaHermano() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_titulo = new javax.swing.JLabel();
        eti_nombre = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        eti_fec_nac = new javax.swing.JLabel();
        combo_familia = new javax.swing.JComboBox();
        eti_familia = new javax.swing.JLabel();
        combo_tIpohermano = new javax.swing.JComboBox();
        eti_tipohermano = new javax.swing.JLabel();
        eti_referencia = new javax.swing.JLabel();
        telefono_txt = new javax.swing.JTextField();
        combo_parentesco = new javax.swing.JComboBox();
        eti_parentesco = new javax.swing.JLabel();
        eti_telefono = new javax.swing.JLabel();
        referencia_txt = new javax.swing.JTextField();
        bt_guardar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        fecha_nac_txt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar Hermano");

        Label_titulo.setFont(new java.awt.Font("Verdana", 1, 14));
        Label_titulo.setText("Agregar nuevo Hermano");

        eti_nombre.setText("Nombre: ");

        eti_fec_nac.setText("Fecha de Nacimiento:");

        eti_familia.setText("Familia:");

        combo_tIpohermano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Miembro", "Asistente" }));
        combo_tIpohermano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tIpohermanoActionPerformed(evt);
            }
        });

        eti_tipohermano.setText("Tipo de Hermano: ");

        eti_referencia.setText("Referencia: ");

        combo_parentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Esposo", "Esposa", "Hijo(a)", "Nieto(a)" }));
        combo_parentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_parentescoActionPerformed(evt);
            }
        });

        eti_parentesco.setText("Parentesco: ");

        eti_telefono.setText("Teléfono:");

        bt_guardar.setText("Guardar");

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eti_nombre)
                            .addComponent(eti_familia)
                            .addComponent(eti_telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eti_fec_nac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_nac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(eti_parentesco))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(combo_familia, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(eti_tipohermano)))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combo_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combo_tIpohermano, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eti_referencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(referencia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_nombre)
                    .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_fec_nac)
                    .addComponent(fecha_nac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_familia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_familia)
                    .addComponent(eti_tipohermano)
                    .addComponent(combo_tIpohermano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_telefono)
                    .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti_parentesco)
                    .addComponent(combo_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_referencia)
                    .addComponent(referencia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancelar)
                    .addComponent(bt_guardar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_tIpohermanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tIpohermanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tIpohermanoActionPerformed

    private void combo_parentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_parentescoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_parentescoActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
         this.doDefaultCloseAction();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JComboBox combo_familia;
    private javax.swing.JComboBox combo_parentesco;
    private javax.swing.JComboBox combo_tIpohermano;
    private javax.swing.JLabel eti_familia;
    private javax.swing.JLabel eti_fec_nac;
    private javax.swing.JLabel eti_nombre;
    private javax.swing.JLabel eti_parentesco;
    private javax.swing.JLabel eti_referencia;
    private javax.swing.JLabel eti_telefono;
    private javax.swing.JLabel eti_tipohermano;
    private javax.swing.JTextField fecha_nac_txt;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JTextField referencia_txt;
    private javax.swing.JTextField telefono_txt;
    // End of variables declaration//GEN-END:variables
}
