/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaFamilia.java
 *
 * Created on 5/05/2011, 09:34:32 PM
 */
package pibxalapa;

/**
 *
 * @author ivan
 */
public class ConsultaFamilia extends javax.swing.JInternalFrame {

    /** Creates new form ConsultaFamilia */
    public ConsultaFamilia() {
        initComponents();
        CargarFamilias();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_titulo = new javax.swing.JLabel();
        combo_familias = new javax.swing.JComboBox();
        Label_titulo1 = new javax.swing.JLabel();
        Label_No_Integrantes = new javax.swing.JLabel();
        num_integrantes_txt = new javax.swing.JTextField();
        Label_calle = new javax.swing.JLabel();
        calle_txt = new javax.swing.JTextField();
        Label_Colonia = new javax.swing.JLabel();
        colonia_combo = new javax.swing.JComboBox();
        Label_Municipio = new javax.swing.JLabel();
        municipio_combo = new javax.swing.JComboBox();
        Label_tel = new javax.swing.JLabel();
        telefono_txt = new javax.swing.JTextField(10);
        bt_eliminaffam = new javax.swing.JButton();
        bt_editarfam = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consultar Familia");

        Label_titulo.setFont(new java.awt.Font("Verdana", 1, 14));
        Label_titulo.setText("Familia:");

        combo_familias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_familiasActionPerformed(evt);
            }
        });

        Label_titulo1.setFont(new java.awt.Font("Verdana", 1, 14));
        Label_titulo1.setText("Consultar Familia");

        Label_No_Integrantes.setText("No. de Integrantes:");

        num_integrantes_txt.setEditable(false);

        Label_calle.setText("Calle y No.:");

        calle_txt.setEditable(false);

        Label_Colonia.setText("Colonia:");

        colonia_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colonia_comboActionPerformed(evt);
            }
        });

        Label_Municipio.setText("Municipio:");

        municipio_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipio_comboActionPerformed(evt);
            }
        });

        Label_tel.setText("Teléfono: ");

        telefono_txt.setEditable(false);

        bt_eliminaffam.setText("Eliminar");
        bt_eliminaffam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminaffamActionPerformed(evt);
            }
        });

        bt_editarfam.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Label_calle))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Label_tel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Label_Colonia)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(colonia_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Label_Municipio))
                                    .addComponent(calle_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_familias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label_No_Integrantes)
                                        .addGap(18, 18, 18)
                                        .addComponent(num_integrantes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(municipio_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Label_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addComponent(bt_eliminaffam, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bt_editarfam, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_titulo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_titulo)
                    .addComponent(combo_familias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_calle)
                    .addComponent(Label_No_Integrantes)
                    .addComponent(num_integrantes_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colonia_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Municipio)
                    .addComponent(municipio_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Colonia))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_tel)
                    .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_editarfam)
                    .addComponent(bt_eliminaffam))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colonia_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colonia_comboActionPerformed
        
    }//GEN-LAST:event_colonia_comboActionPerformed

    private void municipio_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipio_comboActionPerformed
        
}//GEN-LAST:event_municipio_comboActionPerformed

    private void combo_familiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_familiasActionPerformed
           CargarPanelFamilia();
    }//GEN-LAST:event_combo_familiasActionPerformed

    private void bt_eliminaffamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminaffamActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(null, "¿Esta usted seguro de querer eliminar a la familia " +family.Familia+"?", "Advertencia", javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION) {
        try{
            java.sql.Connection conexion = java.sql.DriverManager.getConnection("jdbc:sqlite:"+System.getProperty("user.dir")+"/pibxalapa.db");
            java.sql.Statement instruccion_remove = conexion.createStatement();
            String cad_sql = "Delete from Familia where FamiliaID = "+family.FamiliaID; 
            instruccion_remove.executeUpdate(cad_sql);
            
        }catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e.toString());
        }
            
        }
       LimpiarPanelFamilia();
       //combo_familias.removeItem(combo_familias.getSelectedItem());
       
       
        
       
       
        
    }//GEN-LAST:event_bt_eliminaffamActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Colonia;
    private javax.swing.JLabel Label_Municipio;
    private javax.swing.JLabel Label_No_Integrantes;
    private javax.swing.JLabel Label_calle;
    private javax.swing.JLabel Label_tel;
    private javax.swing.JLabel Label_titulo;
    private javax.swing.JLabel Label_titulo1;
    private javax.swing.JButton bt_editarfam;
    private javax.swing.JButton bt_eliminaffam;
    private javax.swing.JTextField calle_txt;
    private javax.swing.JComboBox colonia_combo;
    private javax.swing.JComboBox combo_familias;
    private javax.swing.JComboBox municipio_combo;
    private javax.swing.JTextField num_integrantes_txt;
    private javax.swing.JTextField telefono_txt;
    // End of variables declaration//GEN-END:variables

private void CargarFamilias(){
    
    java.util.ArrayList<Familia> lista = Familia.ListaFamilias();
		for(Familia familia : lista)
			combo_familias.addItem(familia);

}
Familia family;

private void CargarPanelFamilia(){
    family = (Familia)combo_familias.getSelectedItem();
    this.calle_txt.setText(family.Calle);
    this.num_integrantes_txt.setText(Integer.toString(family.No_Integrantes));
    this.colonia_combo.setEditable(true);
    this.municipio_combo.setEditable(true);
    this.colonia_combo.setSelectedItem(family.Colonia);
    this.municipio_combo.setSelectedItem(family.Municipio);
    this.colonia_combo.setEditable(false);
    this.municipio_combo.setEditable(false);
    this.municipio_combo.setSelectedItem(family.Municipio);
    this.telefono_txt.setText(family.Telefono);
    
    
    
}
private void LimpiarPanelFamilia(){
    this.combo_familias.removeItem(combo_familias.getSelectedItem());
    this.calle_txt.setText("");
    this.num_integrantes_txt.setText("");
    this.colonia_combo.setEditable(true);
    this.colonia_combo.setSelectedItem("");
    this.municipio_combo.setEditable(true);
    this.municipio_combo.setSelectedItem("");
    this.telefono_txt.setText("");
    
}


}
