package pibxalapa;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 30/04/2011, 01:53:44 PM
 */
/**
 *
 * @author ivan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

   
    public VentanaPrincipal() {
        initComponents();
       
        try{
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */ @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        javax.swing.JMenuBar barra_menu = new javax.swing.JMenuBar();
        javax.swing.JMenu Archivo = new javax.swing.JMenu();
        javax.swing.JMenuItem GuardarBD = new javax.swing.JMenuItem();
        javax.swing.JMenuItem CargarBD = new javax.swing.JMenuItem();
        javax.swing.JMenuItem Exit = new javax.swing.JMenuItem();
        javax.swing.JMenu Familias = new javax.swing.JMenu();
        javax.swing.JMenuItem AgregaFam = new javax.swing.JMenuItem();
        javax.swing.JMenuItem BuscaFam = new javax.swing.JMenuItem();
        javax.swing.JMenu Miebros = new javax.swing.JMenu();
        javax.swing.JMenuItem AgregaMiem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem BuscaMiembro = new javax.swing.JMenuItem();
        javax.swing.JMenu Reportes = new javax.swing.JMenu();
        javax.swing.JMenuItem Re_Fam = new javax.swing.JMenuItem();
        javax.swing.JMenuItem Re_Miembros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de Familias -PIB-");
        setResizable(false);

        Archivo.setText("Archivo");

        GuardarBD.setText("Guardar Base de Datos");
        GuardarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBDActionPerformed(evt);
            }
        });
        Archivo.add(GuardarBD);

        CargarBD.setText("Cargar Base de Datos");
        Archivo.add(CargarBD);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Archivo.add(Exit);

        barra_menu.add(Archivo);

        Familias.setText("Familias");

        AgregaFam.setText("Agregar");
        AgregaFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaFamActionPerformed(evt);
            }
        });
        Familias.add(AgregaFam);

        BuscaFam.setText("Buscar");
        BuscaFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaFamActionPerformed(evt);
            }
        });
        Familias.add(BuscaFam);

        barra_menu.add(Familias);

        Miebros.setText("Miembros");

        AgregaMiem.setText("Agregar");
        AgregaMiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaMiemActionPerformed(evt);
            }
        });
        Miebros.add(AgregaMiem);

        BuscaMiembro.setText("Buscar");
        Miebros.add(BuscaMiembro);

        barra_menu.add(Miebros);

        Reportes.setText("Reportes");

        Re_Fam.setText("Familias");
        Reportes.add(Re_Fam);

        Re_Miembros.setText("Miembros");
        Reportes.add(Re_Miembros);

        barra_menu.add(Reportes);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarBDActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
                  if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro de querer abandonar la aplicacion?", "Advertencia", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
					System.exit(0);
				}
    }//GEN-LAST:event_ExitActionPerformed

    private void AgregaFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaFamActionPerformed
           AltaFamilia ventana_alta = new AltaFamilia();
           escritorio.add(ventana_alta);
           ventana_alta.show();
    }//GEN-LAST:event_AgregaFamActionPerformed

    private void AgregaMiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaMiemActionPerformed
        AltaHermano ventana_alta_miembro = new AltaHermano();
           escritorio.add(ventana_alta_miembro);
           ventana_alta_miembro.show();
    }//GEN-LAST:event_AgregaMiemActionPerformed

    private void BuscaFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaFamActionPerformed
        ConsultaFamilia ventana_consultafamilia = new ConsultaFamilia();
           escritorio.add(ventana_consultafamilia);
           ventana_consultafamilia.show();
    }//GEN-LAST:event_BuscaFamActionPerformed

    /**
     * @param args the command line arguments
     */


            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
}
